### ISSUE TITLE
Encryption / Decryption of a message

### ISSUE THREAD

**Issue by Chamaeleo-Calyptratus** [kudelskisecurity/crystals-go#15]
Hi, thanks for your repo. I don't know if I'm doing something wrong. When decrypting, characters are truncated and I only get 32 Bytes.

`

	kyber := kyber.NewKyber1024()
	pk, sk := kyber.PKEKeyGen(nil)
	msg := make([]byte, 44)
	msg = []byte("Very random message to sign in the benchmark")
	encryptMessage := kyber.Encrypt(pk, msg, nil)
	decryptedMessage := kyber.Decrypt(sk, encryptMessage)
	log.Println("HELLO")
	//log.Println(encryptMessage)
	log.Println(len(msg)) // 44 Bytes
	log.Println(len(decryptedMessage)) // 32 Bytes
`

So 'SEEDBYTES' only represents 32. Therefore, is not possible to use longer messages?

**Comment by acheong08** [comment]
The encryption is meant for 32byte keys for symmetric encryption

**Comment by acheong08** [comment]
You can do a workaround to encrypt more than 32bytes but it is very inefficient and creates unreasonably large files

**Comment by acheong08** [comment]
https://github.com/acheong08/crystallize

(My attempt)

**Comment by tgkudelski** [comment]
Hello and thanks for reporting. Please notice that this repository is not maintained anymore, it was part of a MsC thesis project but it was not correctly marked as "unmaintained". Kudelski Security does not use this library in any commercial offering or services, it was just meant for testing and fun. I have now updated the README file to clarify this, and I will now archive this repository to avoid further issues.
