### ISSUE TITLE
Implement crypto.Signer

### ISSUE THREAD

**Issue by theredrad** [kudelskisecurity/crystals-go#17]
Implementing [cyrpto.Signer](https://pkg.go.dev/crypto#Signer) helps to use it for x509 Certificates. 

https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/crypto/x509/x509.go;drc=f375b305c801515b587719490b4be0db1a66e20c;l=1535

Also, the public key should implement crypto.Public key interface (https://pkg.go.dev/crypto#PublicKey)
https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/crypto/x509/x509.go;drc=f375b305c801515b587719490b4be0db1a66e20c;l=1597

I'd like to contribute to that and just logging this here.

**Comment by tgkudelski** [comment]
Hello and thanks for reporting. Please notice that this repository is not maintained anymore, it was part of a MsC thesis project but it was not correctly marked as "unmaintained". Kudelski Security does not use this library in any commercial offering or services, it was just meant for testing and fun. I have now updated the README file to clarify this, and I will now archive this repository to avoid further issues.
