### ISSUE TITLE
Perform error checking, add error returns

### ISSUE THREAD

**Issue by dertseha** [kudelskisecurity/crystals-go#2]
While working on #1 , I found the linters `gosec` and `errcheck` report several cases of omitted error handling.

Properly addressing these errors requires the extension of the public API. For example, `Dilithium.KeyGen()` does not return `error` and (currently) ignores any error return from the internal cryptographic components (rand, sha3).

I understand the library is a "direct" port of the C-reference implementation. I don't know how errors are handled there, yet it is necessary to allow Go-idiomatic error handling.

Due to the necessary API changes the linters are currently excluded. They should be enabled as part of handling this issue to properly find all cases.

Are there any specific concerns, or would a typical extension of `error` as return value be OK?

**Comment by tgkudelski** [comment]
Hello and thanks for reporting. Please notice that this repository is not maintained anymore, it was part of a MsC thesis project but it was not correctly marked as "unmaintained". Kudelski Security does not use this library in any commercial offering or services, it was just meant for testing and fun. I have now updated the README file to clarify this, and I will now archive this repository to avoid further issues.
