### ISSUE TITLE
Clarify use of weak number generator

### ISSUE THREAD

**Issue by dertseha** [kudelskisecurity/crystals-go#3]
While working on #1 , I found the linter `gosec` report the use of a weak number generator (`math/rand` instead of `crypto/rand`).
Several uses are in test, yet this also is in the production code, for example in `Dilithium.KeyGen()`.

Note that because of #2 , the linter `gosec` is not enabled at all. As part of this issue here, consider the state of the other issue and ensure the linter is enabled.

I do not know the details, only that the simple number generator should not be used.
Is there a specific reason that the weaker generator is in use, or can the better one be used instead?

**Comment by PizzaWhisperer** [comment]
If you look at the rand import at L5, https://github.com/kudelskisecurity/crystals-go/blob/main/crystals-dilithium/dilithium3.go#L5, crypto/rand is used.

**Comment by PizzaWhisperer** [comment]
I noticed that math.rand is used once during the tests to generate a seed, I will remove that to uniform the randomness source. But, the integer generation using math/rand.Intn() for testing purposes is not an issue. I am closing the issue.

**Comment by dertseha** [comment]
Ah, my bad, I saw the reports from the linter and assumed it to be a wide-spread issue.
Thank you for clarifying and looking into this.

**Comment by PizzaWhisperer** [comment]
You're welcome
