### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by dertseha** [kudelskisecurity/crystals-go#4]
Several exported functions and types (and the packages themselves) are missing documentation.
In order to properly use the library, documentation is necessary.

I found this while working on #1 , and as such the linter `revive` is disabled, and `stylecheck` has message `ST1000` disabled.

R-use of the information in `README.md` might be a good start. Is this enough?

**Comment by PizzaWhisperer** [comment]
Documentation has been added. Let me know if it is still unclear.

**Comment by dertseha** [comment]
Thank you for following up on this. Documentation is now present, though because I have next to no domain knowledge I cannot rate its quality. (I thus could enable linter `revive` in #1 .)

What is still missing is a package documentation, which could be used to showcase a few usages or general documentation. This could be based on the readme texts.

**Comment by tgkudelski** [comment]
Hello and thanks for reporting. Please notice that this repository is not maintained anymore, it was part of a MsC thesis project but it was not correctly marked as "unmaintained". Kudelski Security does not use this library in any commercial offering or services, it was just meant for testing and fun. I have now updated the README file to clarify this, and I will now archive this repository to avoid further issues.
